# This is a basic workflow to help you get started with Actions

name: Hello World
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "A demo Bro"

  test:
     runs-on: ubuntu-latest
     steps:
      - name: Test step
        run: echo "Running Bro"
        
  deploy:
     runs-on: ubuntu-latest
     steps:
      - name: Deploy step
        run: echo "Deploy Bro"
  
         


