# This is a basic workflow to help you get started with Actions

name: Hello World
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello step
        run: |
         echo "Welcome Bro"
         echo "Welcome Bro"
         echo "Welcome Bro"


